import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Masud um management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //eikhane kono layout add korle globally sob jaygay niye nibe
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
